
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop 
  labels:
    project: roboshop
    environmet: dev
    tire: app
    component: catalogue
spec:
  selector:
    matchLabels:
      project: roboshop
      environmet: dev
      tire: app
      component: catalogue
  template:
    metadata:
      name: catalogue
      namespace: roboshop 
      labels:
        project: roboshop
        environmet: dev
        tire: app
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: "{{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}"
        envFrom:
        - configMapRef:
            name: catalogue
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "150Mi"
          
